# Generated by Django 4.2.5 on 2024-08-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_writeup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='data',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
